version: '3'

services:
  phx:
    build: .
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootp
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "3306:3306"
    volumes:
      - ./stograge/db:/var/lib/mysql
