version: "2"

services:
  arvore:
    build: .
    container_name: arvore
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore_test
      MYSQL_USER: circleci
      MYSQL_PASSWORD: circleci
    ports:
      - "5000:5000"

  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: root
